// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gtn/gtn/game.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Game struct {
	Id                uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CommitmentHash    []byte     `protobuf:"bytes,2,opt,name=commitment_hash,json=commitmentHash,proto3" json:"commitment_hash,omitempty"`
	StartedAtHeight   int64      `protobuf:"varint,3,opt,name=started_at_height,json=startedAtHeight,proto3" json:"started_at_height,omitempty"`
	Duration          int64      `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	EntryFee          types.Coin `protobuf:"bytes,5,opt,name=entry_fee,json=entryFee,proto3" json:"entry_fee"`
	Reward            types.Coin `protobuf:"bytes,6,opt,name=reward,proto3" json:"reward"`
	ParticipantsCount uint64     `protobuf:"varint,7,opt,name=participants_count,json=participantsCount,proto3" json:"participants_count,omitempty"`
	Salt              []byte     `protobuf:"bytes,8,opt,name=salt,proto3" json:"salt,omitempty"`
	Number            uint64     `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	Creator           string     `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_8285eddab4fa593f, []int{0}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Game.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return m.Size()
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetCommitmentHash() []byte {
	if m != nil {
		return m.CommitmentHash
	}
	return nil
}

func (m *Game) GetStartedAtHeight() int64 {
	if m != nil {
		return m.StartedAtHeight
	}
	return 0
}

func (m *Game) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Game) GetEntryFee() types.Coin {
	if m != nil {
		return m.EntryFee
	}
	return types.Coin{}
}

func (m *Game) GetReward() types.Coin {
	if m != nil {
		return m.Reward
	}
	return types.Coin{}
}

func (m *Game) GetParticipantsCount() uint64 {
	if m != nil {
		return m.ParticipantsCount
	}
	return 0
}

func (m *Game) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *Game) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Game) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Game)(nil), "gtn.gtn.Game")
}

func init() { proto.RegisterFile("gtn/gtn/game.proto", fileDescriptor_8285eddab4fa593f) }

var fileDescriptor_8285eddab4fa593f = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3f, 0x8f, 0xd3, 0x30,
	0x14, 0x8f, 0xdb, 0x5c, 0xda, 0x1a, 0x44, 0x55, 0x0b, 0x90, 0xe9, 0x10, 0x22, 0x16, 0xc2, 0x0d,
	0x89, 0x0e, 0x90, 0x58, 0x58, 0xe8, 0x49, 0x70, 0x73, 0x46, 0x96, 0xc8, 0x49, 0x1e, 0x89, 0x25,
	0x6c, 0x47, 0xf6, 0x2b, 0x70, 0x23, 0xdf, 0x80, 0x8f, 0xc1, 0xc8, 0xc7, 0xb8, 0xb1, 0x23, 0x13,
	0x42, 0xed, 0xc0, 0xd7, 0x40, 0x71, 0x03, 0x74, 0x64, 0x48, 0xf4, 0x7e, 0xff, 0x86, 0xdf, 0x7b,
	0xa6, 0xac, 0x45, 0x9d, 0xfb, 0x4f, 0x28, 0xc8, 0x7a, 0x6b, 0xd0, 0xb0, 0x59, 0x8b, 0x3a, 0x6b,
	0x51, 0xaf, 0xef, 0xb6, 0xa6, 0x35, 0x9e, 0xcb, 0x87, 0xe9, 0x28, 0xaf, 0xe3, 0xda, 0x38, 0x65,
	0x5c, 0x5e, 0x09, 0x07, 0xf9, 0x87, 0x8b, 0x0a, 0x50, 0x5c, 0xe4, 0xb5, 0x91, 0x7a, 0xd4, 0x57,
	0x42, 0x49, 0x6d, 0x72, 0xff, 0x3f, 0x52, 0x8f, 0x3e, 0x4f, 0x69, 0xf8, 0x46, 0x28, 0x60, 0xf7,
	0xe8, 0x44, 0x36, 0x9c, 0x24, 0x24, 0x0d, 0x37, 0x67, 0x5f, 0x7f, 0x7d, 0x3b, 0x27, 0xc5, 0x44,
	0x36, 0xec, 0x31, 0x5d, 0xd6, 0x46, 0x29, 0x89, 0x0a, 0x34, 0x96, 0x9d, 0x70, 0x1d, 0x9f, 0x24,
	0x24, 0xbd, 0x5d, 0xdc, 0xf9, 0x47, 0x5f, 0x09, 0xd7, 0xb1, 0x73, 0xba, 0x72, 0x28, 0x2c, 0x42,
	0x53, 0x0a, 0x2c, 0x3b, 0x90, 0x6d, 0x87, 0x7c, 0x9a, 0x90, 0x74, 0x5a, 0x2c, 0x47, 0xe1, 0x15,
	0x5e, 0x79, 0x9a, 0xad, 0xe9, 0xbc, 0xd9, 0x5a, 0x81, 0xd2, 0x68, 0x1e, 0x7a, 0xcb, 0x5f, 0xcc,
	0x5e, 0xd2, 0x05, 0x68, 0xb4, 0xd7, 0xe5, 0x3b, 0x00, 0x7e, 0x96, 0x90, 0xf4, 0xd6, 0xd3, 0x07,
	0xd9, 0xb1, 0x57, 0x36, 0xf4, 0xca, 0xc6, 0x5e, 0xd9, 0xa5, 0x91, 0x7a, 0x13, 0xde, 0xfc, 0x78,
	0x18, 0x14, 0x73, 0x9f, 0x78, 0x0d, 0xc0, 0x5e, 0xd0, 0xc8, 0xc2, 0x47, 0x61, 0x1b, 0x1e, 0xfd,
	0x5f, 0x74, 0xb4, 0xb3, 0xe7, 0x94, 0xf5, 0xc2, 0xa2, 0xac, 0x65, 0x2f, 0x34, 0xba, 0xb2, 0x36,
	0x5b, 0x8d, 0x7c, 0x76, 0xba, 0x8e, 0xd5, 0xa9, 0xe1, 0x72, 0xd0, 0x19, 0xa3, 0xa1, 0x13, 0xef,
	0x91, 0xcf, 0xfd, 0x4a, 0xfc, 0xcc, 0xee, 0xd3, 0x48, 0x6f, 0x55, 0x05, 0x96, 0x2f, 0x86, 0x74,
	0x31, 0x22, 0xc6, 0xe9, 0xac, 0xb6, 0x20, 0xd0, 0x58, 0x4e, 0x13, 0x92, 0x2e, 0x8a, 0x3f, 0x70,
	0xf3, 0xe4, 0x66, 0x1f, 0x93, 0xdd, 0x3e, 0x26, 0x3f, 0xf7, 0x31, 0xf9, 0x72, 0x88, 0x83, 0xdd,
	0x21, 0x0e, 0xbe, 0x1f, 0xe2, 0xe0, 0xed, 0x72, 0xb8, 0xff, 0x27, 0xff, 0x0a, 0xf0, 0xba, 0x07,
	0x57, 0x45, 0xfe, 0x6a, 0xcf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x27, 0x84, 0xa1, 0xa4, 0x1d,
	0x02, 0x00, 0x00,
}

func (m *Game) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Game) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Game) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x52
	}
	if m.Number != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x42
	}
	if m.ParticipantsCount != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.ParticipantsCount))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.Reward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGame(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.EntryFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGame(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Duration != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x20
	}
	if m.StartedAtHeight != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.StartedAtHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CommitmentHash) > 0 {
		i -= len(m.CommitmentHash)
		copy(dAtA[i:], m.CommitmentHash)
		i = encodeVarintGame(dAtA, i, uint64(len(m.CommitmentHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGame(dAtA []byte, offset int, v uint64) int {
	offset -= sovGame(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Game) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGame(uint64(m.Id))
	}
	l = len(m.CommitmentHash)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.StartedAtHeight != 0 {
		n += 1 + sovGame(uint64(m.StartedAtHeight))
	}
	if m.Duration != 0 {
		n += 1 + sovGame(uint64(m.Duration))
	}
	l = m.EntryFee.Size()
	n += 1 + l + sovGame(uint64(l))
	l = m.Reward.Size()
	n += 1 + l + sovGame(uint64(l))
	if m.ParticipantsCount != 0 {
		n += 1 + sovGame(uint64(m.ParticipantsCount))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.Number != 0 {
		n += 1 + sovGame(uint64(m.Number))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func sovGame(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGame(x uint64) (n int) {
	return sovGame(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Game) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Game: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Game: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentHash = append(m.CommitmentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitmentHash == nil {
				m.CommitmentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartedAtHeight", wireType)
			}
			m.StartedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EntryFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantsCount", wireType)
			}
			m.ParticipantsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticipantsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGame(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGame
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGame
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGame
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGame
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGame        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGame          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGame = fmt.Errorf("proto: unexpected end of group")
)
